const boiDataInputs = [
  {
    _id: "323",
    type: "text",
    placeholder: "title",
    // onChange: handleLand,
    name: "title",
    labelText: "Title",
    // value: formValues.title,
  },
  {
    _id: "wdids",
    type: "number",
    placeholder: "Bedrooms",
    // onChange: handleLand,
    name: "bedrooms",
    labelText: "Bedrooms",
    // value: formValues.bedrooms,
  },
  {
    _id: "wids",
    type: "number",
    placeholder: "Bathroom",
    // onChange: handleLand,
    name: "bathrooms",
    labelText: "Bathrooms",
    // value: formValues.bathrooms,
  },
  {
    _id: "323hd",
    type: "text",
    placeholder: "Landmark",
    onChange: handleLand,
    name: "landmark",
    labelText: "Landmark",
    // value: formValues.landmark,
  },
  {
    _id: "323KKDhd",
    type: "text",
    placeholder: "e.g city...",
    onChange: handleLand,
    name: "city",
    labelText: "City",
    // value: formValues.city,
  },
  {
    _id: "33423",
    type: "text",
    placeholder: "street name",
    // onChange: handleLand,
    name: "streetName",
    labelText: "street name",
    // value: formValues.streetName,
  },
  {
    _id: "33423",
    type: "number",
    placeholder: "price",
    // onChange: handleLand,
    name: "price",
    labelText: "Price",
    // value: formValues.price,
  },
  {
    _id: "wids",
    type: "number",
    placeholder: "land size in sqft only",
    // onChange: handleLand,
    name: "landSize",
    labelText: "Land size (sqft)",
    // value: formValues.landSize,
  },

  {
    _id: "323kwdids",
    type: "text",
    placeholder: "Local government area",
    // onChange: handleLand,
    name: "lga",
    labelText: "local government area",
    // value: formValues.lga,
  },

  {
    _id: "323kwdids",
    type: "select",
    placeholder: "status",
    // onChange: handleLand,
    name: "status",
    labelText: "status",
    // value: formValues.status,
    helperText: "select property status",
    options: [
      {
        text: "FOR SALE",
        value: "FOR SALE",
      },
      {
        text: "FOR RENT",
        value: "FOR RENT",
      },
    ],
  },

  {
    _id: "323kwdids",
    type: "textarea",
    placeholder: "property description",
    // onChange: handleLand,
    name: "description",
    labelText: "property description",
    // value: formValues.description,
  },
];
